import type { Metadata, Viewport } from "next";
import { Inter } from "next/font/google";
import { RouteProvider } from "@/old/providers/router-provider";
import { Theme } from "@/old/providers/theme";
import { WebSocketProvider } from "@/old/providers/websocket-provider";
import "@/old/styles/globals.css";
import { cx } from "@/old/utils/cx";

const inter = Inter({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-inter",
});

export const metadata: Metadata = {
  title: "Starter kit — Untitled UI",
  description: "Generated by Untitled UI CLI",
};

export const viewport: Viewport = {
  themeColor: "#7f56d9",
  colorScheme: "light",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <link rel="manifest" href="/manifest.webmanifest" />
        <meta name="theme-color" content="#000000" />

        {/* iOS PWA */}
        <meta name="apple-mobile-web-app-capable" content="yes" />
        <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent" />
        <link rel="apple-touch-icon" href="/icons/icon.png" />
        <meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover" />
      </head>
      <body className={cx(inter.variable, "bg-primary antialiased")}>
        <RouteProvider>
          <Theme>
            <WebSocketProvider>{children}</WebSocketProvider>
          </Theme>
        </RouteProvider>
      </body>
    </html>
  );
}
